-- Create the read-only 2025 historical leads table (odd/tasks/historico-2025.md, T1).
-- This migration is intentionally NOT applied by this repository.
-- Review it in the Supabase SQL editor before applying it to the remote project.

begin;

create table if not exists public.leads_historico (
  id bigint generated by default as identity primary key,

  -- Same names as public.leads, including the trailing space in "OBSERVACIONES ".
  "Mes" text,
  "Fecha" text,
  "Nombre" text,
  "Apellido" text,
  "Telefono" text,
  "Campaña" text,
  "Medio" text,
  "GESTION" text,
  "AGENTE" text,
  "Odoo" text,
  "Fecha de Atencion" text,
  "OBSERVACIONES " text,

  -- Import audit metadata.
  source_year smallint not null default 2025,
  source_file text,
  source_row integer,
  imported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Immutable generation expressions (PostgreSQL 15): coalesce() is an expression and
  -- regexp_replace(text, text, text, text) is immutable (pg_proc provolatile default 'i').
  telefono_normalizado text generated always as (regexp_replace(coalesce("Telefono", ''), '\D', '', 'g')) stored,
  -- Declared after id and source_year. PostgreSQL only rejects references to another
  -- generated column or to system columns; identity columns (attgenerated = '\0') are
  -- allowed, so no plain column + unique constraint fallback is needed. Uniqueness is
  -- inherent in the value: 'historico_' || source_year || '_' || id with id as primary key.
  registro_key text generated always as ('historico_' || source_year::text || '_' || id::text) stored
);

create index if not exists leads_historico_telefono_norm_idx
  on public.leads_historico (telefono_normalizado)
  where telefono_normalizado <> '';

create index if not exists leads_historico_source_year_mes_idx
  on public.leads_historico (source_year, "Mes");

alter table public.leads_historico enable row level security;

-- Read-only history: SELECT for active authenticated users only. There is no
-- archived_at column on this table, so the policy carries no archive condition.
-- There is intentionally no INSERT/UPDATE/DELETE policy.
drop policy if exists "leads_historico_read_active_authorized" on public.leads_historico;
create policy "leads_historico_read_active_authorized"
on public.leads_historico for select to authenticated
using (public.is_active_user());

revoke insert, update, delete on public.leads_historico from anon, authenticated;
grant select on public.leads_historico to authenticated;

comment on table public.leads_historico is
  'Read-only 2025 historical leads imported from the source CSV; the app never writes to it. Relates to public.leads by telefono_normalizado (digits only) and is audited via source_year/source_file/source_row.';

commit;

-- Rollback (manual, after review): drop the policy, the two indexes and the table
-- only if no imported data must be kept. Do not run this automatically against
-- the remote project.
